image: node:latest
build:
  stage: build
  script:
    - npm install
    - ./node_modules/.bin/gatsby build --prefix-paths
  artifacts:
    paths:
      - public
pages:
  stage: deploy
  script:
    - echo "Hello"
  artifacts:
    paths:
      - public
  only:
    - master
