image: node:latest
build:
  stage: build
  script:
    - npm install
pages:
  stage: deploy
  script:
    - ./node_modules/.bin/gatsby build --prefix-paths
  artifacts:
    paths:
      - public
  only:
    - master
